### ISSUE TITLE
Excluded PR

### ISSUE THREAD

**Issue by HellspawnXerxes** [ossamamehmood/Hacktoberfest2022#523]
Hey @ossamamehmood I am getting the status of my PR as excluded. How to correct it?

**Comment by ItzLevvie** [comment]
This repository has been excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards Hacktoberfest 2022.

Please contribute to valuable repositories instead of sending pull requests (PRs) to repositories that are there to defeat the purpose of Hacktoberfest 2022.

Any repeated exclusions will automatically ban your account from Hacktoberfest 2022.

**Comment by ossamamehmood** [comment]
> Hey @ossamamehmood I am getting the status of my PR as excluded. How to correct it?

Just Forked and Merge things on your own fork to get your PR considered!
